#!/bin/bash
# 创建所有 __init__.py 使目录成为 Python 包
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

touch "$ROOT/pipeline/__init__.py"
touch "$ROOT/pipeline/api_parser/__init__.py"
touch "$ROOT/pipeline/sdk_parser/__init__.py"
touch "$ROOT/pipeline/embedder/__init__.py"
touch "$ROOT/pipeline/knowledge_builder/__init__.py"
touch "$ROOT/server/__init__.py"
touch "$ROOT/server/app/__init__.py"
touch "$ROOT/server/app/rag/__init__.py"
touch "$ROOT/server/app/llm/__init__.py"
touch "$ROOT/server/app/rerank/__init__.py"
touch "$ROOT/server/app/embedding/__init__.py"
touch "$ROOT/server/app/embedding/providers/__init__.py"
touch "$ROOT/server/app/intent/__init__.py"
touch "$ROOT/server/app/knowledge/__init__.py"
touch "$ROOT/server/app/prompts/__init__.py"
touch "$ROOT/server/app/db/__init__.py"
touch "$ROOT/server/app/api/__init__.py"
touch "$ROOT/server/frontend/__init__.py"
